export {default as Site} from './Site/Site';
export {default as YaMaps} from './Site/YaMaps';
export {default as TopSite} from './TopSite';
export {default as Pages} from './Site/Pages';
export {default as MenuGoods} from './Goods/MenuGoods';
export {default as CartRoot} from './Cart/CartRoot';
export {default as GoodsOptions} from './Goods/GoodsOptions';
export {default as GoodsArea} from './Goods/GoodsArea';
export {default as Slider} from './Slider/Slider1';