export {default as Header} from './Header/Header';
export {default as Cart} from './Cart/Cart';
export {default as CartItem} from './Cart/CartItem';
export {default as Footer} from './Footer/Footer';
export {default as Nav } from './Nav/Nav';
export {default as GoodsCard } from './Goods/GoodsCard';
export {default as GoodsList } from './Goods/GoodsList';
export {default as GoodsBlock } from './Goods/GoodsBlock';
export {default as LoadingBlock } from './Goods/LoadingBlock';
export {default as About} from './Pages/About';
export {default as Contakts} from './Pages/Contakts';
export {default as Delivery} from './Pages/Delivery';
export {default as Sale} from './Pages/Sale';
export {default as HappyHours} from './Pages/HappyHours';
